package projecteuler;

public class PE002 {
//	Each new term in the Fibonacci sequence is generated by adding 
//	the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//	By considering the terms in the Fibonacci sequence whose values do not exceed 
//  four million, find the sum of the even-valued terms.

	public static void main(String[] args) {
		System.out.println("The sum of the even valued Fibonacci numbers");
		System.out.println("whose values do not exceed 4 million is: " + findSumOfEvenValuedFibs(4_000_000));
		System.out.println("Confirmed answer from Project Euler: 4613732");
	}
	
	public static int findSumOfEvenValuedFibs(int upperLimit){
		int n1 = 1, n2 = 2;
		int sum = 2;
		while (n2 < upperLimit){
			int temp = n1;
			n1 = n2;
			n2 = temp + n1;
			if (n2 % 2 == 0) sum += n2;
		}
		return sum;
	}
}
